python-cli: add `print-cache-dir` subcommand
pyocd/cmsis-pack-manager pull request #178
Opened 2021-09-29 16:52 UTC by noahp

Add a subcommand to the python cli that prints out the cache directory.

This is useful for locating the downloaded packs for extracting
files from them without using the library.

It should be roughly equivalent to:

```bash
❯ python -c \
  'import cmsis_pack_manager; print(cmsis_pack_manager.Cache(False, False).data_path)'
```

Added a test to cover it.

2021-09-29 19:36 UTC, theotherjimmy approved these changes
I love that you added tests!

2021-09-29 19:42 UTC, flit requested changes
All the code looks great.

I'd appreciate if you could add your copyright to the modified files, below the existing copyrights.

2021-09-30 13:08 UTC, noahp commented
> All the code looks great.
> 
> I'd appreciate if you could add your copyright to the modified files, below the existing copyrights.

:+1: added it to the file that had copyright notices (the test file did not, let me know if I should add it there too!)

2021-09-30 15:50 UTC, mathias-arm approved these changes

2021-10-01 18:41 UTC, flit approved these changes

2021-10-01 19:09 UTC, merged