Switch from webpki-roots to rustls-native-certs
pyocd/cmsis-pack-manager pull request #185
Opened 2021-12-28 21:21 UTC by claymation

Fixes #184.

2021-12-29 16:30 UTC, mathias-arm requested changes

2021-12-29 16:30 UTC, mathias-arm commented on rust/cmsis-pack/Cargo.toml
> +reqwest = { version = "0.11.0", default_features = false, features = ["rustls-tls-native-certs", "trust-dns", "stream"] }
I think the feature in `reqwest` is called `rustls-tls-native-roots` and uses the `rustls-tls-native-certs` crate.

2021-12-30 20:48 UTC, mathias-arm approved these changes
Not a fan of "transparent" TLS proxies, but honoring the system trust preferences seems like a good thing. This change will probably need additional cross-platform testing.

2023-07-30 22:50 UTC, kand198 commented
I'd like to lend a hand in getting this merged, if possible.

I have tested these changes on `Ubuntu 22.04.2 LTS on Windows 10 x86_64` (WSL2).

What further testing would you like to see?

2023-08-02 15:19 UTC, mathias-arm commented
@claymation, @kand198: I rebased the PR. If you could test that it still fixes the issue and that there are no regressions (in particular on Windows).

2023-08-07 02:21 UTC, kand198 commented
I have re-tested under Windows 10 natively (non-WSL), as well as Ubuntu 22.04 under WSL2. Everything builds and runs fine. I can update packs from behind my work proxy. Tests pass.

2023-08-07 14:14 UTC, merged